project_id = "wuvbrkbhunifudaewhng"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.delete-user]
verify_jwt = false

[functions.emergency-cleanup]
verify_jwt = false